/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	time "time"

	cerebralcontainershipiov1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	versioned "github.com/containership/cerebral/pkg/client/clientset/versioned"
	internalinterfaces "github.com/containership/cerebral/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/containership/cerebral/pkg/client/listers/cerebral.containership.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// AutoscalingPolicyInformer provides access to a shared informer and lister for
// AutoscalingPolicies.
type AutoscalingPolicyInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.AutoscalingPolicyLister
}

type autoscalingPolicyInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
}

// NewAutoscalingPolicyInformer constructs a new informer for AutoscalingPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewAutoscalingPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredAutoscalingPolicyInformer(client, resyncPeriod, indexers, nil)
}

// NewFilteredAutoscalingPolicyInformer constructs a new informer for AutoscalingPolicy type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredAutoscalingPolicyInformer(client versioned.Interface, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CerebralV1alpha1().AutoscalingPolicies().List(options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.CerebralV1alpha1().AutoscalingPolicies().Watch(options)
			},
		},
		&cerebralcontainershipiov1alpha1.AutoscalingPolicy{},
		resyncPeriod,
		indexers,
	)
}

func (f *autoscalingPolicyInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredAutoscalingPolicyInformer(client, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *autoscalingPolicyInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&cerebralcontainershipiov1alpha1.AutoscalingPolicy{}, f.defaultInformer)
}

func (f *autoscalingPolicyInformer) Lister() v1alpha1.AutoscalingPolicyLister {
	return v1alpha1.NewAutoscalingPolicyLister(f.Informer().GetIndexer())
}
