---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: containership-core
  name: cerebral
  labels:
    containership.io/app: cerebral
    containership.io/managed: "true"
    app.kubernetes.io/name: cerebral
    app.kubernetes.io/part-of: cerebral
spec:
  replicas: 1
  selector:
    matchLabels:
      containership.io/app: cerebral
      containership.io/managed: "true"
      app.kubernetes.io/name: cerebral
      app.kubernetes.io/part-of: cerebral
  template:
    metadata:
      labels:
        containership.io/app: cerebral
        containership.io/managed: "true"
        app.kubernetes.io/name: cerebral
        app.kubernetes.io/part-of: cerebral
    spec:
      serviceAccountName: containership-admin
      tolerations:
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
      nodeSelector:
        node-role.kubernetes.io/master: ""
      containers:
      - name: cerebral
        image: containership/cerebral:latest
        imagePullPolicy: Always
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: CONTAINERSHIP_CLOUD_CLUSTER_API_KEY
          valueFrom:
            secretKeyRef:
              name: cerebral-containership-engine
              key: CONTAINERSHIP_CLOUD_CLUSTER_API_KEY
