// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Engine is an autogenerated mock type for the Engine type
type Engine struct {
	mock.Mock
}

// Name provides a mock function with given fields:
func (_m *Engine) Name() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// SetTargetNodeCount provides a mock function with given fields: nodeSelector, numNodes, strategy
func (_m *Engine) SetTargetNodeCount(nodeSelector map[string]string, numNodes int, strategy string) (bool, error) {
	ret := _m.Called(nodeSelector, numNodes, strategy)

	var r0 bool
	if rf, ok := ret.Get(0).(func(map[string]string, int, string) bool); ok {
		r0 = rf(nodeSelector, numNodes, strategy)
	} else {
		r0 = ret.Get(0).(bool)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(map[string]string, int, string) error); ok {
		r1 = rf(nodeSelector, numNodes, strategy)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
