apiVersion: cerebral.containership.io/v1alpha1
kind: AutoscalingPolicy
metadata:
  name: prometheus-cpu-percentage
spec:
  metricsBackend: prometheus
  metric: cpu
  metricConfiguration:
    aggregation: avg
  policy:
    scaleUp:
      threshold: 0.8
      comparisonOperator: ">="
      adjustmentType: percent
      adjustmentValue: 100
    scaleDown:
      threshold: 0.35
      comparisonOperator: "<"
      adjustmentType: absolute
      adjustmentValue: 1
      heuristic: leastPods
  pollInterval: 15
  samplePeriod: 600
