/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAutoscalingEngines implements AutoscalingEngineInterface
type FakeAutoscalingEngines struct {
	Fake *FakeCerebralV1alpha1
}

var autoscalingenginesResource = schema.GroupVersionResource{Group: "cerebral.containership.io", Version: "v1alpha1", Resource: "autoscalingengines"}

var autoscalingenginesKind = schema.GroupVersionKind{Group: "cerebral.containership.io", Version: "v1alpha1", Kind: "AutoscalingEngine"}

// Get takes name of the autoscalingEngine, and returns the corresponding autoscalingEngine object, and an error if there is any.
func (c *FakeAutoscalingEngines) Get(name string, options v1.GetOptions) (result *v1alpha1.AutoscalingEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootGetAction(autoscalingenginesResource, name), &v1alpha1.AutoscalingEngine{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AutoscalingEngine), err
}

// List takes label and field selectors, and returns the list of AutoscalingEngines that match those selectors.
func (c *FakeAutoscalingEngines) List(opts v1.ListOptions) (result *v1alpha1.AutoscalingEngineList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootListAction(autoscalingenginesResource, autoscalingenginesKind, opts), &v1alpha1.AutoscalingEngineList{})
	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AutoscalingEngineList{}
	for _, item := range obj.(*v1alpha1.AutoscalingEngineList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested autoscalingEngines.
func (c *FakeAutoscalingEngines) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewRootWatchAction(autoscalingenginesResource, opts))
}

// Create takes the representation of a autoscalingEngine and creates it.  Returns the server's representation of the autoscalingEngine, and an error, if there is any.
func (c *FakeAutoscalingEngines) Create(autoscalingEngine *v1alpha1.AutoscalingEngine) (result *v1alpha1.AutoscalingEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootCreateAction(autoscalingenginesResource, autoscalingEngine), &v1alpha1.AutoscalingEngine{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AutoscalingEngine), err
}

// Update takes the representation of a autoscalingEngine and updates it. Returns the server's representation of the autoscalingEngine, and an error, if there is any.
func (c *FakeAutoscalingEngines) Update(autoscalingEngine *v1alpha1.AutoscalingEngine) (result *v1alpha1.AutoscalingEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootUpdateAction(autoscalingenginesResource, autoscalingEngine), &v1alpha1.AutoscalingEngine{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AutoscalingEngine), err
}

// Delete takes name of the autoscalingEngine and deletes it. Returns an error if one occurs.
func (c *FakeAutoscalingEngines) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewRootDeleteAction(autoscalingenginesResource, name), &v1alpha1.AutoscalingEngine{})
	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAutoscalingEngines) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewRootDeleteCollectionAction(autoscalingenginesResource, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AutoscalingEngineList{})
	return err
}

// Patch applies the patch and returns the patched autoscalingEngine.
func (c *FakeAutoscalingEngines) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoscalingEngine, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewRootPatchSubresourceAction(autoscalingenginesResource, name, data, subresources...), &v1alpha1.AutoscalingEngine{})
	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AutoscalingEngine), err
}
