apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: autoscalinggroups.cerebral.containership.io
spec:
  group: cerebral.containership.io
  version: v1alpha1
  names:
    kind: AutoScalingGroup
    listKind: AutoScalingGroupList
    singular: autoscalinggroup
    plural: autoscalinggroups
    shortNames:
    - asg
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            nodeSelector:
              type: object
            policies:
              type: array
              items:
                type: string
            engine:
              type: string
            suspend:
              type: boolean
            cooldownPeriod:
              type: integer
            maxNodes:
              type: integer
              minimum: 0
            minNodes:
              type: integer
              minimum: 0

  subresources:
    status: {}
