/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	scheme "github.com/containership/cerebral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AutoscalingPoliciesGetter has a method to return a AutoscalingPolicyInterface.
// A group's client should implement this interface.
type AutoscalingPoliciesGetter interface {
	AutoscalingPolicies() AutoscalingPolicyInterface
}

// AutoscalingPolicyInterface has methods to work with AutoscalingPolicy resources.
type AutoscalingPolicyInterface interface {
	Create(*v1alpha1.AutoscalingPolicy) (*v1alpha1.AutoscalingPolicy, error)
	Update(*v1alpha1.AutoscalingPolicy) (*v1alpha1.AutoscalingPolicy, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AutoscalingPolicy, error)
	List(opts v1.ListOptions) (*v1alpha1.AutoscalingPolicyList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoscalingPolicy, err error)
	AutoscalingPolicyExpansion
}

// autoscalingPolicies implements AutoscalingPolicyInterface
type autoscalingPolicies struct {
	client rest.Interface
}

// newAutoscalingPolicies returns a AutoscalingPolicies
func newAutoscalingPolicies(c *CerebralV1alpha1Client) *autoscalingPolicies {
	return &autoscalingPolicies{
		client: c.RESTClient(),
	}
}

// Get takes name of the autoscalingPolicy, and returns the corresponding autoscalingPolicy object, and an error if there is any.
func (c *autoscalingPolicies) Get(name string, options v1.GetOptions) (result *v1alpha1.AutoscalingPolicy, err error) {
	result = &v1alpha1.AutoscalingPolicy{}
	err = c.client.Get().
		Resource("autoscalingpolicies").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AutoscalingPolicies that match those selectors.
func (c *autoscalingPolicies) List(opts v1.ListOptions) (result *v1alpha1.AutoscalingPolicyList, err error) {
	result = &v1alpha1.AutoscalingPolicyList{}
	err = c.client.Get().
		Resource("autoscalingpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested autoscalingPolicies.
func (c *autoscalingPolicies) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("autoscalingpolicies").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a autoscalingPolicy and creates it.  Returns the server's representation of the autoscalingPolicy, and an error, if there is any.
func (c *autoscalingPolicies) Create(autoscalingPolicy *v1alpha1.AutoscalingPolicy) (result *v1alpha1.AutoscalingPolicy, err error) {
	result = &v1alpha1.AutoscalingPolicy{}
	err = c.client.Post().
		Resource("autoscalingpolicies").
		Body(autoscalingPolicy).
		Do().
		Into(result)
	return
}

// Update takes the representation of a autoscalingPolicy and updates it. Returns the server's representation of the autoscalingPolicy, and an error, if there is any.
func (c *autoscalingPolicies) Update(autoscalingPolicy *v1alpha1.AutoscalingPolicy) (result *v1alpha1.AutoscalingPolicy, err error) {
	result = &v1alpha1.AutoscalingPolicy{}
	err = c.client.Put().
		Resource("autoscalingpolicies").
		Name(autoscalingPolicy.Name).
		Body(autoscalingPolicy).
		Do().
		Into(result)
	return
}

// Delete takes name of the autoscalingPolicy and deletes it. Returns an error if one occurs.
func (c *autoscalingPolicies) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("autoscalingpolicies").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *autoscalingPolicies) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("autoscalingpolicies").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched autoscalingPolicy.
func (c *autoscalingPolicies) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoscalingPolicy, err error) {
	result = &v1alpha1.AutoscalingPolicy{}
	err = c.client.Patch(pt).
		Resource("autoscalingpolicies").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
