/*
Copyright 2019 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	scheme "github.com/containership/cerebral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AutoscalingEnginesGetter has a method to return a AutoscalingEngineInterface.
// A group's client should implement this interface.
type AutoscalingEnginesGetter interface {
	AutoscalingEngines() AutoscalingEngineInterface
}

// AutoscalingEngineInterface has methods to work with AutoscalingEngine resources.
type AutoscalingEngineInterface interface {
	Create(*v1alpha1.AutoscalingEngine) (*v1alpha1.AutoscalingEngine, error)
	Update(*v1alpha1.AutoscalingEngine) (*v1alpha1.AutoscalingEngine, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AutoscalingEngine, error)
	List(opts v1.ListOptions) (*v1alpha1.AutoscalingEngineList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoscalingEngine, err error)
	AutoscalingEngineExpansion
}

// autoscalingEngines implements AutoscalingEngineInterface
type autoscalingEngines struct {
	client rest.Interface
}

// newAutoscalingEngines returns a AutoscalingEngines
func newAutoscalingEngines(c *CerebralV1alpha1Client) *autoscalingEngines {
	return &autoscalingEngines{
		client: c.RESTClient(),
	}
}

// Get takes name of the autoscalingEngine, and returns the corresponding autoscalingEngine object, and an error if there is any.
func (c *autoscalingEngines) Get(name string, options v1.GetOptions) (result *v1alpha1.AutoscalingEngine, err error) {
	result = &v1alpha1.AutoscalingEngine{}
	err = c.client.Get().
		Resource("autoscalingengines").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AutoscalingEngines that match those selectors.
func (c *autoscalingEngines) List(opts v1.ListOptions) (result *v1alpha1.AutoscalingEngineList, err error) {
	result = &v1alpha1.AutoscalingEngineList{}
	err = c.client.Get().
		Resource("autoscalingengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested autoscalingEngines.
func (c *autoscalingEngines) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("autoscalingengines").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a autoscalingEngine and creates it.  Returns the server's representation of the autoscalingEngine, and an error, if there is any.
func (c *autoscalingEngines) Create(autoscalingEngine *v1alpha1.AutoscalingEngine) (result *v1alpha1.AutoscalingEngine, err error) {
	result = &v1alpha1.AutoscalingEngine{}
	err = c.client.Post().
		Resource("autoscalingengines").
		Body(autoscalingEngine).
		Do().
		Into(result)
	return
}

// Update takes the representation of a autoscalingEngine and updates it. Returns the server's representation of the autoscalingEngine, and an error, if there is any.
func (c *autoscalingEngines) Update(autoscalingEngine *v1alpha1.AutoscalingEngine) (result *v1alpha1.AutoscalingEngine, err error) {
	result = &v1alpha1.AutoscalingEngine{}
	err = c.client.Put().
		Resource("autoscalingengines").
		Name(autoscalingEngine.Name).
		Body(autoscalingEngine).
		Do().
		Into(result)
	return
}

// Delete takes name of the autoscalingEngine and deletes it. Returns an error if one occurs.
func (c *autoscalingEngines) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("autoscalingengines").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *autoscalingEngines) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("autoscalingengines").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched autoscalingEngine.
func (c *autoscalingEngines) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoscalingEngine, err error) {
	result = &v1alpha1.AutoscalingEngine{}
	err = c.client.Patch(pt).
		Resource("autoscalingengines").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
