/*
Copyright 2018 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	scheme "github.com/containership/cerebral/pkg/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AutoScalingGroupsGetter has a method to return a AutoScalingGroupInterface.
// A group's client should implement this interface.
type AutoScalingGroupsGetter interface {
	AutoScalingGroups() AutoScalingGroupInterface
}

// AutoScalingGroupInterface has methods to work with AutoScalingGroup resources.
type AutoScalingGroupInterface interface {
	Create(*v1alpha1.AutoScalingGroup) (*v1alpha1.AutoScalingGroup, error)
	Update(*v1alpha1.AutoScalingGroup) (*v1alpha1.AutoScalingGroup, error)
	UpdateStatus(*v1alpha1.AutoScalingGroup) (*v1alpha1.AutoScalingGroup, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AutoScalingGroup, error)
	List(opts v1.ListOptions) (*v1alpha1.AutoScalingGroupList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoScalingGroup, err error)
	AutoScalingGroupExpansion
}

// autoScalingGroups implements AutoScalingGroupInterface
type autoScalingGroups struct {
	client rest.Interface
}

// newAutoScalingGroups returns a AutoScalingGroups
func newAutoScalingGroups(c *CerebralV1alpha1Client) *autoScalingGroups {
	return &autoScalingGroups{
		client: c.RESTClient(),
	}
}

// Get takes name of the autoScalingGroup, and returns the corresponding autoScalingGroup object, and an error if there is any.
func (c *autoScalingGroups) Get(name string, options v1.GetOptions) (result *v1alpha1.AutoScalingGroup, err error) {
	result = &v1alpha1.AutoScalingGroup{}
	err = c.client.Get().
		Resource("autoscalinggroups").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AutoScalingGroups that match those selectors.
func (c *autoScalingGroups) List(opts v1.ListOptions) (result *v1alpha1.AutoScalingGroupList, err error) {
	result = &v1alpha1.AutoScalingGroupList{}
	err = c.client.Get().
		Resource("autoscalinggroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested autoScalingGroups.
func (c *autoScalingGroups) Watch(opts v1.ListOptions) (watch.Interface, error) {
	opts.Watch = true
	return c.client.Get().
		Resource("autoscalinggroups").
		VersionedParams(&opts, scheme.ParameterCodec).
		Watch()
}

// Create takes the representation of a autoScalingGroup and creates it.  Returns the server's representation of the autoScalingGroup, and an error, if there is any.
func (c *autoScalingGroups) Create(autoScalingGroup *v1alpha1.AutoScalingGroup) (result *v1alpha1.AutoScalingGroup, err error) {
	result = &v1alpha1.AutoScalingGroup{}
	err = c.client.Post().
		Resource("autoscalinggroups").
		Body(autoScalingGroup).
		Do().
		Into(result)
	return
}

// Update takes the representation of a autoScalingGroup and updates it. Returns the server's representation of the autoScalingGroup, and an error, if there is any.
func (c *autoScalingGroups) Update(autoScalingGroup *v1alpha1.AutoScalingGroup) (result *v1alpha1.AutoScalingGroup, err error) {
	result = &v1alpha1.AutoScalingGroup{}
	err = c.client.Put().
		Resource("autoscalinggroups").
		Name(autoScalingGroup.Name).
		Body(autoScalingGroup).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *autoScalingGroups) UpdateStatus(autoScalingGroup *v1alpha1.AutoScalingGroup) (result *v1alpha1.AutoScalingGroup, err error) {
	result = &v1alpha1.AutoScalingGroup{}
	err = c.client.Put().
		Resource("autoscalinggroups").
		Name(autoScalingGroup.Name).
		SubResource("status").
		Body(autoScalingGroup).
		Do().
		Into(result)
	return
}

// Delete takes name of the autoScalingGroup and deletes it. Returns an error if one occurs.
func (c *autoScalingGroups) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Resource("autoscalinggroups").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *autoScalingGroups) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	return c.client.Delete().
		Resource("autoscalinggroups").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched autoScalingGroup.
func (c *autoScalingGroups) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AutoScalingGroup, err error) {
	result = &v1alpha1.AutoScalingGroup{}
	err = c.client.Patch(pt).
		Resource("autoscalinggroups").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
