/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/containership/cerebral/pkg/apis/cerebral.containership.io/v1alpha1"
	"github.com/containership/cerebral/pkg/client/clientset/versioned/scheme"
	rest "k8s.io/client-go/rest"
)

type CerebralV1alpha1Interface interface {
	RESTClient() rest.Interface
	AutoscalingEnginesGetter
	AutoscalingGroupsGetter
	AutoscalingPoliciesGetter
	MetricsBackendsGetter
}

// CerebralV1alpha1Client is used to interact with features provided by the cerebral.containership.io group.
type CerebralV1alpha1Client struct {
	restClient rest.Interface
}

func (c *CerebralV1alpha1Client) AutoscalingEngines() AutoscalingEngineInterface {
	return newAutoscalingEngines(c)
}

func (c *CerebralV1alpha1Client) AutoscalingGroups() AutoscalingGroupInterface {
	return newAutoscalingGroups(c)
}

func (c *CerebralV1alpha1Client) AutoscalingPolicies() AutoscalingPolicyInterface {
	return newAutoscalingPolicies(c)
}

func (c *CerebralV1alpha1Client) MetricsBackends() MetricsBackendInterface {
	return newMetricsBackends(c)
}

// NewForConfig creates a new CerebralV1alpha1Client for the given config.
func NewForConfig(c *rest.Config) (*CerebralV1alpha1Client, error) {
	config := *c
	if err := setConfigDefaults(&config); err != nil {
		return nil, err
	}
	client, err := rest.RESTClientFor(&config)
	if err != nil {
		return nil, err
	}
	return &CerebralV1alpha1Client{client}, nil
}

// NewForConfigOrDie creates a new CerebralV1alpha1Client for the given config and
// panics if there is an error in the config.
func NewForConfigOrDie(c *rest.Config) *CerebralV1alpha1Client {
	client, err := NewForConfig(c)
	if err != nil {
		panic(err)
	}
	return client
}

// New creates a new CerebralV1alpha1Client for the given RESTClient.
func New(c rest.Interface) *CerebralV1alpha1Client {
	return &CerebralV1alpha1Client{c}
}

func setConfigDefaults(config *rest.Config) error {
	gv := v1alpha1.SchemeGroupVersion
	config.GroupVersion = &gv
	config.APIPath = "/apis"
	config.NegotiatedSerializer = scheme.Codecs.WithoutConversion()

	if config.UserAgent == "" {
		config.UserAgent = rest.DefaultKubernetesUserAgent()
	}

	return nil
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *CerebralV1alpha1Client) RESTClient() rest.Interface {
	if c == nil {
		return nil
	}
	return c.restClient
}
