---
apiVersion: cerebral.containership.io/v1alpha1
kind: AutoscalingPolicy
metadata:
  name: prometheus-cpu-percent-utilization
spec:
  metricsBackend: prometheus
  metric: cpu
  metricConfiguration:
    aggregation: avg
  pollInterval: 15
  samplePeriod: 600
  scalingPolicy:
    scaleDown:
      threshold: 35
      comparisonOperator: "<"
      adjustmentType: absolute
      adjustmentValue: 1
    scaleUp:
      threshold: 80
      comparisonOperator: ">="
      adjustmentType: percent
      adjustmentValue: 100
