apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: autoscalingpolicies.cerebral.containership.io
spec:
  group: cerebral.containership.io
  names:
    kind: AutoscalingPolicy
    listKind: AutoscalingPolicyList
    singular: autoscalingpolicy
    plural: autoscalingpolicies
    shortNames:
    - asp
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  subresources:
    status: {}
