apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: metricsbackends.cerebral.containership.io
spec:
  group: cerebral.containership.io
  names:
    kind: MetricsBackend
    listKind: MetricsBackendList
    singular: metricsbackend
    plural: metricsbackends
    shortNames:
    - mb
  scope: Cluster
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
            - type
          properties:
            type:
              type: string
            configuration:
              type: object
